export const CONTRACT_ID = "CDIGDTCOY3J6YHVXXBKK7NWLSLYHYV3OAPMSWHQJTPKQ4QBY4QVV4GL3";
export const PAYMENT_TOKEN_ID = "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC";

export const seedState = {
  merchants: [
    {
      id: "merchant_an_coffee",
      name: "An Coffee Da Nang",
      location: "Da Nang, Vietnam",
      category: "Cafe checkout pilot",
      contact: "ops@ancoffee.example",
    },
    {
      id: "merchant_weekend_market",
      name: "Weekend Market HCMC",
      location: "Ho Chi Minh City, Vietnam",
      category: "Event retail",
      contact: "market@weekend.example",
    },
    {
      id: "merchant_green_campus",
      name: "Green Campus Club",
      location: "Hue, Vietnam",
      category: "Student event",
      contact: "club@campus.example",
    },
  ],
  campaigns: [
    {
      projectId: 1,
      merchantId: "merchant_an_coffee",
      title: "Da Nang Solar Classroom",
      merchant: "An Coffee Da Nang",
      location: "Da Nang, Vietnam",
      status: "Live on Testnet",
      category: "Solar education",
      checkoutSlug: "solar-classroom",
      checkoutChannel: "Cafe checkout pilot",
      contractBacked: true,
      network: "TESTNET",
      contractId: CONTRACT_ID,
      paymentToken: PAYMENT_TOKEN_ID,
      pricePerVoucher: 1000000,
      unitPerVoucher: 10,
      impactUnit: "kWh of verified solar energy",
      vouchersSold: 2,
      fundedAmount: 2000000,
      verifiedUnits: 20,
      withdrawnAmount: 1000000,
      refundedAmount: 0,
      payoutReadyAmount: 1000000,
      reportHash: "ipfs://solar-meter-report-june-v2",
      updatedAt: "2026-06-17T00:00:00.000Z",
    },
    {
      projectId: 2,
      merchantId: "merchant_weekend_market",
      title: "Can Gio Mangrove Revival",
      merchant: "Weekend Market HCMC",
      location: "Ho Chi Minh City, Vietnam",
      status: "Preview campaign",
      category: "Mangrove restoration",
      checkoutSlug: "mangrove-revival",
      checkoutChannel: "Weekend market QR stand",
      contractBacked: false,
      network: "Product preview",
      contractId: null,
      paymentToken: PAYMENT_TOKEN_ID,
      pricePerVoucher: 1500000,
      unitPerVoucher: 3,
      impactUnit: "m2 of mangrove restoration",
      vouchersSold: 48,
      fundedAmount: 72000000,
      verifiedUnits: 0,
      withdrawnAmount: 0,
      refundedAmount: 0,
      payoutReadyAmount: 0,
      reportHash: "Pending verifier report",
      updatedAt: "2026-06-17T00:00:00.000Z",
    },
    {
      projectId: 3,
      merchantId: "merchant_green_campus",
      title: "Campus Refill Station",
      merchant: "Green Campus Club",
      location: "Hue, Vietnam",
      status: "Draft checkout",
      category: "Plastic reduction",
      checkoutSlug: "campus-refill",
      checkoutChannel: "Student event checkout",
      contractBacked: false,
      network: "Product preview",
      contractId: null,
      paymentToken: PAYMENT_TOKEN_ID,
      pricePerVoucher: 800000,
      unitPerVoucher: 12,
      impactUnit: "single-use bottles avoided",
      vouchersSold: 25,
      fundedAmount: 20000000,
      verifiedUnits: 120,
      withdrawnAmount: 0,
      refundedAmount: 0,
      payoutReadyAmount: 0,
      reportHash: "ipfs://campus-refill-audit-preview",
      updatedAt: "2026-06-17T00:00:00.000Z",
    },
  ],
  checkoutSessions: [],
  receipts: [
    {
      voucherId: "voucher-1",
      projectId: 1,
      buyer: "GDZN36...E5JFK",
      campaign: "Da Nang Solar Classroom",
      merchant: "An Coffee Da Nang",
      paidAmount: 1000000,
      impactAmount: 10,
      impactUnit: "kWh of verified solar energy",
      transactionHash: "472998d13bce42752cd682ae63b074f21348c6ffec719a23de79348398f51702",
      verificationStatus: "verified",
      refundStatus: "not_requested",
      reportHash: "ipfs://solar-meter-report-june-v2",
      issuedAt: "2026-06-17T00:00:00.000Z",
    },
  ],
  indexedTransactions: [
    {
      hash: "472998d13bce42752cd682ae63b074f21348c6ffec719a23de79348398f51702",
      label: "Buy voucher",
      projectId: 1,
      source: "seed-proof",
      status: "SUCCESS",
      syncedAt: "2026-06-17T00:00:00.000Z",
    },
    {
      hash: "bfe5b3cfa4a2b5e52d236ab20c801cefee685880dfc5a837f2fc24927a65952c",
      label: "Verify project",
      projectId: 1,
      source: "seed-proof",
      status: "SUCCESS",
      syncedAt: "2026-06-17T00:00:00.000Z",
    },
    {
      hash: "8f2a42d3a58291cf19d1b3b39d536fc2e490a3a87c24d5d8ac0163aa0420744b",
      label: "Retire voucher",
      projectId: 1,
      source: "seed-proof",
      status: "SUCCESS",
      syncedAt: "2026-06-17T00:00:00.000Z",
    },
    {
      hash: "cea81936292151d40393a9eba007f71e24408e826fdf96ff4363c811094ca3b5",
      label: "Withdraw funds",
      projectId: 1,
      source: "seed-proof",
      status: "SUCCESS",
      syncedAt: "2026-06-17T00:00:00.000Z",
    },
  ],
};
