export const PROJECT_ID = 1;

export const demoProject = {
  owner: "GDZN36SJ6LJURNUNBW47MQF3DZQDAOGSTZIQVABZLMOVJLN4HZZE5JFK",
  title: "Da Nang Solar Classroom",
  impact_unit: "kWh of verified solar energy",
  metadata_hash: "ipfs://solar-classroom-metadata-v2",
  report_hash: "ipfs://solar-meter-report-june-v2",
  payment_token: "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC",
  price_per_voucher: 1000000,
  unit_per_voucher: 10,
  vouchers_sold: 2,
  funded_amount: 2000000,
  withdrawn_amount: 1000000,
  verified_units: 20,
  retired_units: 20,
};

export const demoHolding = {
  vouchers_owned: 2,
  active_vouchers: 0,
  retired_vouchers: 2,
  active_units: 0,
  retired_units: 20,
  paid_amount: 2000000,
};

export const demoCampaigns = [
  {
    projectId: PROJECT_ID,
    title: "Da Nang Solar Classroom",
    merchant: "An Coffee Da Nang",
    location: "Da Nang, Vietnam",
    status: "Live on Testnet",
    category: "Solar education",
    checkoutSlug: "solar-classroom",
    checkoutChannel: "Cafe checkout pilot",
    contractBacked: true,
    pricePerVoucher: demoProject.price_per_voucher,
    unitPerVoucher: demoProject.unit_per_voucher,
    impactUnit: demoProject.impact_unit,
    vouchersSold: demoProject.vouchers_sold,
    fundedAmount: demoProject.funded_amount,
    verifiedUnits: demoProject.verified_units,
    withdrawnAmount: demoProject.withdrawn_amount,
    reportHash: demoProject.report_hash,
  },
  {
    projectId: 2,
    title: "Can Gio Mangrove Revival",
    merchant: "Weekend Market HCMC",
    location: "Ho Chi Minh City, Vietnam",
    status: "Preview campaign",
    category: "Mangrove restoration",
    checkoutSlug: "mangrove-revival",
    checkoutChannel: "Weekend market QR stand",
    contractBacked: false,
    pricePerVoucher: 1500000,
    unitPerVoucher: 3,
    impactUnit: "m2 of mangrove restoration",
    vouchersSold: 48,
    fundedAmount: 72000000,
    verifiedUnits: 0,
    withdrawnAmount: 0,
    reportHash: "Pending verifier report",
  },
  {
    projectId: 3,
    title: "Campus Refill Station",
    merchant: "Green Campus Club",
    location: "Hue, Vietnam",
    status: "Draft checkout",
    category: "Plastic reduction",
    checkoutSlug: "campus-refill",
    checkoutChannel: "Student event checkout",
    contractBacked: false,
    pricePerVoucher: 800000,
    unitPerVoucher: 12,
    impactUnit: "single-use bottles avoided",
    vouchersSold: 25,
    fundedAmount: 20000000,
    verifiedUnits: 120,
    withdrawnAmount: 0,
    reportHash: "ipfs://campus-refill-audit-preview",
  },
];
